# Generated by Django 3.2.5 on 2021-07-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descriptionA', models.CharField(max_length=1000)),
                ('descriptionB', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/')),
                ('posted_at', models.DateField()),
                ('stars', models.SmallIntegerField(choices=[(1, 'One star'), (2, 'Two stars'), (3, 'Three stars'), (4, 'four_stars'), (5, 'five stars')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=150)),
                ('sent_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/')),
                ('prep_time', models.CharField(max_length=150)),
                ('cook_time', models.CharField(max_length=150)),
                ('posted_at', models.DateField(auto_now_add=True)),
                ('stars', models.SmallIntegerField(choices=[(1, 'One star'), (2, 'Two stars'), (3, 'Three stars'), (4, 'Four stars'), (5, 'Five stars')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('order', models.IntegerField()),
                ('recipe', models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.IntegerField()),
                ('recipe', models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.recipe')),
            ],
        ),
    ]
