# Generated by Django 3.2.5 on 2021-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
